config/routes.rb
Rails.application.routes.draw do
  get 'transactions/index'
  get 'transactions/create'
  get 'transactions/destroy'
  resources :transactions

  namespace :api do
    resource :session, only: [:create]
    resources :transactions, only: [:create]
  end

  resource :session, only: [:create, :destroy]
  get '/login', to: 'sessions#new'


  root to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
# == Schema Information
#
# Table name: transactions
#
#  id           :bigint           not null, primary key
#  description  :string
#  amount_cents :integer
#  currency     :string
#  date         :datetime
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Transaction < ApplicationRecord
  CURRENCIES = %w{ USD ARS EUR }.freeze
  belongs_to :user

  validates :amount, presence: true
  validates :date,   presence: true

  def amount
    amount_cents && (amount_cents / 100)
  end

  def amount=(val)
    self.amount_cents = val * 100
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string
#  password_digest :string
#  api_token       :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_secure_password

  before_create :set_api_token

  private

  def set_api_token
    self.api_token = SecureRandom.hex(Rails.env.production? ? 64 : 6)
  end
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ApplicationController
    before_action :authenticate_user!

    def authenticate_user!
      if current_user.blank?
        head :unauthorized
      end
    end
  end
end

app/controllers/api/sessions_controller.rb
module Api
  class SessionsController < BaseController
    skip_before_action :authenticate_user!

    def create
      @user = UserAuthenticator.run(session_params)
      if @user
        render json: { session: @user.attributes.slice('email', 'api_token') },
               status: :created
      else
        head :unprocessable_entity
      end
    end

    private

    def session_params
      params.require(:session).permit(:email, :password)
    end
  end
end

app/controllers/api/transactions_controller.rb
module Api
  class TransactionsController < BaseController
    def create
      service = TransactionCreator.new(current_user, transaction_params)
      if service.run
        head :created
      else
        render json: { errors: service.errors }, status: :unprocessable_entity
      end
    end

    private

    def transaction_params
      params.require(:transaction).permit(
        :description, :amount, :currency, :date
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def authenticate_user!
    if current_user.blank?
      redirect_to login_path
    end
  end
end

app/controllers/concerns/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
  end

  def current_user
    @current_user ||= session[:user_id] && User.find_by_id(session[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_signed_in, except: :destroy

  def new
  end

  def create
    @user = UserAuthenticator.run(session_params)
    if @user
      sign_in(@user)
      redirect_to root_path
    else
      flash[:error] = 'Your email and password combination is incorrect'
      @session = OpenStruct.new(session_params)
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to transactions_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

  def redirect_if_signed_in
    redirect_to transactions_path if current_user.present?
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def create
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name:"viewport", content:"width=device-width, initial-scale=1, shrink-to-fit=no"}/
    %title Wimm
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans:400,600,700'
  %body{class: "#{params['controller']}__#{params['action']}"}
    %header.navbar.navbar-light.bg-light.navbar-expand-lg
      %a.navbar-brand{ href: root_path } Wimm
      %ul.navbar-nav.ml-auto
        %li.nav-item
          %a.nav-link.active{ href: '#' } Dashboard
        %li.nav-item
          %a.nav-link Settings
        %li.nav-item
          = link_to "Logout", session_path, method: 'delete', class: 'nav-link'
    .main-content.container
      = yield

app/views/layouts/public.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name:"viewport", content:"width=device-width, initial-scale=1, shrink-to-fit=no"}/
    %title Wimm
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans:400,600,700'
  %body{class: "#{params['controller']}__#{params['action']}"}
    %header.navbar.navbar-light.bg-light.navbar-expand-lg
      %a.navbar-brand{ href: root_path } Wimm

    .main-content.container
      = yield

app/views/transactions/index.html.haml
#app

.create-transaction.container
  .form-row
    .form-group.col-3
      %label Category
      %select.form-control{type: 'select'}
        %option Takeout

    .form-group.col
      %label Date
      %input.form-control{type: 'text'}

    .form-group.col
      %label Description
      %input.form-control{type: 'text'}

    .form-group.col
      %label Account
      %select.form-control{type: 'select'}
        %option Francés USD

    .form-group.col
      %label Amount
      %input.form-control{type: 'text'}

    .form-group.col-auto
      %label Currency
      %select.form-control{type: 'select'}
        %option USD

  .form-row
    .col.justify-content-end
    %button.button__success.add-transaction Add transaction

.transactions-table.container
  .row.header
    .col.col.date
      %span Jun 2018
    .col.col.balance
      %span -28,321.00 ARS
  - 5.times do |i|
    .row.transaction
      .col.col-lg-auto
        %span
          %input{ type: 'checkbox' }
      .col.col-lg-auto.icon
        %i.material-icons.md-36 face
      .col.col-lg-2
        %span Takeout
      .col.col-lg-auto.date
        .abolute Jun 8, 2018
        .relative 2 days ago
      .col
        %span Hamburguesa
      .col.amount
        %span -123.13 ARS
    - if i == 3
      .row.day-separator
        .col